Adding Components
Snayak7643/Cart pull request #1
Opened 2023-01-10 14:12 UTC by Snayak7643

2023-01-12 06:40 UTC, Ishaan-flyfin requested changes

2023-01-12 06:40 UTC, Ishaan-flyfin commented on src/type.ts
> +export type productType = {
nice!

2023-01-12 06:40 UTC, Ishaan-flyfin commented on src/App.tsx
> +      type: ACTIONS.SET_INITIAL,
we can calculate amount and total within SET_INITIAL reducer

2023-01-12 06:40 UTC, Ishaan-flyfin commented on src/Constants/InitialCartState.tsx
> +  total: 2599.96,
we can keep it [],0,0

2023-01-12 06:40 UTC, Ishaan-flyfin commented on src/Reducers/functions.tsx
> +};
export const increaseAmount = (id:number, amount: number, price: number) => {
  return {
        type: ACTIONS.SET_INITIAL,
        payload: { id, amount, price },
  }
}

2023-01-12 06:40 UTC, Ishaan-flyfin commented on src/Reducers/reducer.tsx
> +import { State, Action } from "../type";
change extension to .ts

2023-01-12 06:40 UTC, Ishaan-flyfin commented on src/Components/Product.tsx
> +  const { id, img, title, price } = product;
nice!

2023-01-12 06:40 UTC, Ishaan-flyfin commented on src/Components/ProductList/index.tsx
> +    );
we are repeating this code
instead we can keep heading in app.js  and only return list from here

2023-01-12 06:40 UTC, Ishaan-flyfin commented on src/Components/ProductList/components/Product.tsx
> +              payload: { id, amount: 1, price },
we can remove `amount: 1,`

2023-01-12 06:40 UTC, Ishaan-flyfin commented on src/Components/ProductList/components/Product.tsx
> +            });
we can remnove this

2023-01-12 06:40 UTC, Ishaan-flyfin commented on src/Reducers/actions.ts
> +    }),
we can update total,amount here

2023-01-12 06:40 UTC, Ishaan-flyfin commented on src/Reducers/actions.ts
> +  return {
get product from id and fetch its price, quantity

2023-01-12 06:40 UTC, Ishaan-flyfin commented on src/type.ts
> +  amount: number;
we can rename it to quantity

2023-01-12 06:40 UTC, Ishaan-flyfin commented on src/type.ts
> +  amount: number;
we can rename it to totalQuantity

2023-01-12 07:34 UTC, Snayak7643 commented on src/App.tsx
> +      type: ACTIONS.SET_INITIAL,
done

2023-01-12 07:34 UTC, Snayak7643 commented on src/Constants/InitialCartState.tsx
> +  total: 2599.96,
done

2023-01-12 07:37 UTC, Snayak7643 commented on src/Reducers/functions.tsx
> +};
done

2023-01-12 07:37 UTC, Snayak7643 commented on src/Reducers/reducer.tsx
> +import { State, Action } from "../type";
done

2023-01-12 07:56 UTC, Snayak7643 commented on src/type.ts
> +  amount: number;
done

2023-01-12 07:56 UTC, Snayak7643 commented on src/type.ts
> +  amount: number;
done

2023-01-12 07:57 UTC, Snayak7643 commented on src/Components/ProductList/components/Product.tsx
> +            });
done

2023-01-12 09:31 UTC, Snayak7643 commented on src/Reducers/actions.ts
> +  return {
done

2023-01-12 09:45 UTC, Snayak7643 commented on src/Reducers/actions.ts
> +    }),
done

2023-01-12 09:46 UTC, Snayak7643 commented on src/Components/ProductList/components/Product.tsx
> +              payload: { id, amount: 1, price },
done

2023-01-12 10:16 UTC, Snayak7643 commented on src/Components/ProductList/index.tsx
> +    );
done

2023-01-13 04:29 UTC, Ishaan-flyfin requested changes

2023-01-13 04:29 UTC, Ishaan-flyfin commented on src/Reducers/reducer.ts
> +  const { id, quantity } = action.payload;
we can avoid quantity as well

2023-01-13 04:29 UTC, Ishaan-flyfin commented on src/Reducers/reducer.ts
> +    }
nice

2023-01-13 04:29 UTC, Ishaan-flyfin commented on src/Reducers/actions.ts
> +export const decreaseAmount = (id: number, quantity: number) => {
quantity can be avoided here

2023-01-13 04:29 UTC, Ishaan-flyfin commented on src/Reducers/actions.ts
> +export const set_initial = (productsData: productType[]) => {
for nameing variables, function lets use camelCase

2023-01-13 04:29 UTC, Ishaan-flyfin commented on src/Components/ProductList/components/Product.tsx
> +            }
onClick function does not have return type of dispatch
so instead `return dispatch(remove(id, 1));`
 we can do
```
dispatch(remove(id, 1));
return
```

2023-01-13 04:29 UTC, Ishaan-flyfin commented on src/Components/ProductList/components/Product.tsx
> +    dispatch({ type: ACTIONS.REMOVE, payload: { id, quantity: 0, price: 0 } });
do we need this now?

2023-01-13 05:38 UTC, Ishaan-flyfin approved these changes

2023-01-13 05:49 UTC, merged